---
# tasks file for docker-swarm-centos7

- name: main | updating /etc/hosts (localhost)
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644

- name: update all packages
  yum: name="*" state=latest

- name: Install docker required packages
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - elinks

- name: Add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0440

- name: Install docker required packages
  yum: name=docker-ce state=present

- name: start docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: turn off firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: initiate manager
  command: docker swarm init --advertise-addr "{{ manager_IP }}" 
  when: inventory_hostname == manager